# Generated by Django 6.0.3 on 2026-03-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '활동 소식',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='사진')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '갤러리',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('role', models.CharField(choices=[('president', '회장'), ('vice', '부회장'), ('member', '부원')], default='member', max_length=20, verbose_name='직책')),
                ('belt', models.CharField(blank=True, choices=[('1', '1단'), ('2', '2단'), ('3', '3단'), ('4', '4단'), ('5', '5단')], max_length=10, verbose_name='단수')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('photo', models.ImageField(blank=True, upload_to='members/', verbose_name='사진')),
                ('intro', models.TextField(blank=True, verbose_name='한마디')),
            ],
            options={
                'verbose_name': '부원',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_new', models.BooleanField(default=True, verbose_name='NEW 표시')),
            ],
            options={
                'verbose_name': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
