# Generated by Django 6.0.3 on 2026-03-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('role', models.CharField(choices=[('President', '회장'), ('Vice', '부회장'), ('Secretary', '총무'), ('PR Manager', '홍보부장'), ('Coach', '훈련부장')], default='President', max_length=20, verbose_name='직책')),
                ('belt', models.CharField(blank=True, choices=[('1', '1단'), ('2', '2단'), ('3', '3단'), ('4', '4단'), ('5', '5단')], max_length=10, verbose_name='단수')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('photo', models.ImageField(blank=True, upload_to='members/', verbose_name='사진')),
                ('intro', models.TextField(blank=True, verbose_name='한마디')),
            ],
            options={
                'verbose_name': '임원진',
                'ordering': ['role', 'name'],
            },
        ),
    ]
