# Generated by Django 6.0.3 on 2026-03-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='generation',
            field=models.PositiveIntegerField(default=40, verbose_name='기수'),
            preserve_default=False,
        ),
    ]
