# Generated by Django 6.0.3 on 2026-03-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_member_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('1_President', '회장'), ('2_Vice', '부회장'), ('3_Secretary', '총무'), ('4_PR Manager', '홍보부장'), ('5_Coach', '훈련부장')], default='President', max_length=20, verbose_name='직책'),
        ),
    ]
