# Generated by Django 6.0.3 on 2026-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_activity_image_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='NEW 표시'),
        ),
    ]
