# Generated by Django 6.0.3 on 2026-03-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_activity_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '갤러리'},
        ),
    ]
