# Generated by Django 6.0.3 on 2026-03-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('1_President', '회장'), ('2_Vice', '부회장'), ('3_Secretary', '총무'), ('4_PR Manager', '홍보부장'), ('5_Coach', '훈련부장')], default='1_President', max_length=20, verbose_name='직책'),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity/', verbose_name='사진')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.activity', verbose_name='활동 보고')),
            ],
            options={
                'verbose_name': '활동 사진',
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice/', verbose_name='사진')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.notice', verbose_name='공지사항')),
            ],
            options={
                'verbose_name': '공지 사진',
            },
        ),
    ]
